name: Java CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          DB_DATABASE: ParkingDB
          DB_USER: 'spq'
          DB_PASSWORD: 'spq'
          DB_HOST: 'localhost'
        ports:
          - 3306:3306


    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE SCHEMA ParkingDB;" -uroot -proot
          mysql -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';" -uroot -proot
          mysql -e "GRANT ALL ON ParkingDB.* TO 'spq'@'localhost';" -uroot -proot
          mysql -e "SHOW DATABASES;" -uroot -proot

      - name: Crear la pantalla virtual
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Build with Maven
        run: |
          mvn --batch-mode --update-snapshots compile 
          mvn --batch-mode --update-snapshots datanucleus:enhance
          mvn --batch-mode --update-snapshots datanucleus:schema-create
      - name: Test Unitarios
        run: mvn --batch-mode --update-snapshots test 
      - name: Test Integracion
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/database.sql
          mvn --batch-mode --update-snapshots verify -P integration
      - name: Test Ventanas
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < src/main/resources/database.sql
          mvn --batch-mode --update-snapshots verify -P gui  
        env:
          DISPLAY: ':99'
      - name: Install doxygen
        run: sudo apt-get install -y doxygen
      - name: Install graphviz
        run: sudo apt-get install -y graphviz
      - name: Test with Maven
        run: mvn test -DargLine="-Dcontiperf.active=false"
      - name: Generate documentation
        run: mvn doxygen:report
      - name: Publish on Github Pages
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: target/doxygen/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  
